### ISSUE TITLE
error tambah buku

### ISSUE THREAD

**Issue by ariefansori** [akhwan90/perpus2014#1]
error saat penambahan buku

**Comment by Karla02** [comment]
Fatal error: Uncaught Error: Call to undefined function mysql_pconnect() in C:\xampp\htdocs\perpus-master\system\database\drivers\mysql\mysql_driver.php:91 Stack trace: #0 C:\xampp\htdocs\perpus-master\system\database\DB_driver.php(115): CI_DB_mysql_driver->db_pconnect() #1 C:\xampp\htdocs\perpus-master\system\database\DB.php(148): CI_DB_driver->initialize() #2 C:\xampp\htdocs\perpus-master\system\core\Loader.php(346): DB(Array, NULL) #3 C:\xampp\htdocs\perpus-master\system\core\Loader.php(1171): CI_Loader->database() #4 C:\xampp\htdocs\perpus-master\system\core\Loader.php(152): CI_Loader->_ci_autoloader() #5 C:\xampp\htdocs\perpus-master\system\core\Controller.php(51): CI_Loader->initialize() #6 C:\xampp\htdocs\perpus-master\application\controllers\depan.php(5): CI_Controller->__construct() #7 C:\xampp\htdocs\perpus-master\system\core\CodeIgniter.php(308): Depan->__construct() #8 C:\xampp\htdocs\perpus-master\index.php(202): require_once('C:\\xampp\\htdocs...') #9 {main} thrown in C:\xampp\htdocs\perpus-master\system\database\drivers\mysql\mysql_driver.php on line 91
